# Generated by Django 2.1.7 on 2019-03-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KattisHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KattisScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kattis_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.KattisHandle')),
            ],
        ),
        migrations.AddIndex(
            model_name='kattisscore',
            index=models.Index(fields=['created_at'], name='scoreboard__created_39b405_idx'),
        ),
    ]
