# Generated by Django 2.1.7 on 2019-04-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kattishandle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
